/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { createApiKey } from "../../funcs/createApiKey.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateApiKeyRequest$inboundSchema,
};

export const tool$createApiKey: ToolDefinition<typeof args> = {
  name: "create-api-key",
  description: `Create API Key

Create a new API key`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await createApiKey(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
