/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { listApiKeys } from "../../funcs/listApiKeys.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$listApiKeys: ToolDefinition = {
  name: "list-api-keys",
  description: `List API Keys

List all API keys for the user`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await listApiKeys(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
